import { t } from '../i18n/strings.js';

export default function MethodologyPage({ metadata, locale }) {
  const copy = t(locale);
  const uk = locale === 'uk';
  return <div className="page methodology-page">
    <section className="methodology-hero"><p className="eyebrow">SESH 2023/24</p><h1>{copy.methodologyTitle}</h1><p>{uk ? 'Дашборд дає зважені описові оцінки для населення та домогосподарств на підконтрольній території України.' : 'The dashboard provides weighted descriptive estimates for people and households in government-controlled territory of Ukraine.'}</p></section>
    <div className="methodology-layout">
      <aside><nav aria-label={uk ? 'Зміст методології' : 'Methodology contents'}><a href="#coverage">{uk ? 'Охоплення' : 'Coverage'}</a><a href="#units">{uk ? 'Одиниці й ваги' : 'Units and weights'}</a><a href="#income">{uk ? 'Доходи' : 'Income'}</a><a href="#missing">{uk ? 'Пропуски' : 'Missing values'}</a><a href="#privacy">{uk ? 'Приватність і ліцензія' : 'Privacy and licence'}</a></nav></aside>
      <article>
        <section id="coverage"><h2>{uk ? 'Кого охоплює SESH' : 'Who SESH covers'}</h2><p>{metadata.territory[locale]}</p><p>{uk ? 'Польовий етап тривав із грудня 2023 до лютого 2024 року. Вибірка репрезентативна на національному рівні, за макрорегіонами та типом поселення. Це зріз, а не часовий ряд.' : 'Fieldwork ran from December 2023 through February 2024. The sample is representative nationally, by macro-region and settlement type. This is a cross-section, not a time series.'}</p></section>
        <section id="units"><h2>{uk ? 'Люди й домогосподарства — два окремі знаменники' : 'People and households use separate denominators'}</h2><div className="method-cards"><div><strong>18,837</strong><span>{uk ? 'людей' : 'people'}</span></div><div><strong>8,023</strong><span>{uk ? 'домогосподарства' : 'households'}</span></div></div><p>{uk ? 'Вага WGT_Fin_NEW застосовується без зовнішнього множника. Сума ваг усіх людей оцінює населення; сума ваг одного запису на домогосподарство — кількість домогосподарств. Дашборд ніколи не переносить вагу або знаменник з однієї одиниці на іншу.' : 'WGT_Fin_NEW is used directly, without an external multiplier. Summing all person weights estimates the population; summing one record per household estimates households. The dashboard never transfers weights or denominators across units.'}</p></section>
        <section id="income"><h2>{uk ? 'Три визначення доходу' : 'Three income definitions'}</h2><dl><dt>{uk ? 'Сукупний місячний дохід домогосподарства' : 'Total monthly household income'}</dt><dd>V1.</dd><dt>{uk ? 'Простий дохід на особу' : 'Simple income per person'}</dt><dd>V1 / household size. {uk ? 'Це не еквівалентний дохід OECD.' : 'This is not OECD-equivalised income.'}</dd><dt>{uk ? 'Основний особистий місячний дохід' : 'Main personal monthly income'}</dt><dd>IND_V1_1_1. {uk ? '«Не маю індивідуального доходу» дорівнює нулю; відмови лишаються пропусками.' : '“No personal income” equals zero; refusals remain missing.'}</dd></dl><p>{uk ? 'Додаткові та сезонні доходи у версії 1 не підсумовуються: їхня маршрутизація відрізняється, а частка невизначених відповідей вища.' : 'Version 1 does not add supplementary or seasonal income because routing differs and undefined responses are more common.'}</p></section>
        <section id="missing"><h2>{uk ? 'Пропуск — не «ні»' : 'Missing does not mean “no”'}</h2><p>{uk ? 'Кожний показник має власний universe. Відповіді поза маршрутом анкети та пропуски вилучаються зі знаменника й рахуються окремо. Для числових показників показано зважені p10, p25, медіану, p75, p90 та CDF.' : 'Each indicator has its own universe. Out-of-route and missing responses are excluded from the denominator and counted separately. Numeric indicators show weighted p10, p25, median, p75, p90 and a CDF.'}</p><table><thead><tr><th>n</th><th>{uk ? 'Режим' : 'Display rule'}</th></tr></thead><tbody><tr><td>&lt;10</td><td>{copy.veryLow}</td></tr><tr><td>10–29</td><td>{copy.caution}</td></tr><tr><td>≥30</td><td>{copy.reliable}</td></tr></tbody></table><p>{uk ? 'Усі значення показуються. Ці попередження залежать від незваженої кількості спостережень. Для оцінок людей також показано кількість унікальних домогосподарств-кластерів.' : 'All values remain visible. These warnings use the unweighted observation count. Person estimates also report the number of unique household clusters.'}</p></section>
        <section id="privacy"><h2>{uk ? 'Приватність, джерело й ліцензія' : 'Privacy, source and licence'}</h2><p>{uk ? 'Публічні JSON не містять сирого ключа анкети, телефонів, відкритих текстів, довільних назв професій, районів або точних локацій. Ключі домогосподарств замінено послідовним технічним ID.' : 'Public JSON files exclude raw questionnaire keys, phone numbers, open text, free-text occupations, districts and precise locations. Household keys are replaced by sequential technical IDs.'}</p><p><a href={metadata.source.url} target="_blank" rel="noreferrer">{metadata.source.name}</a>. {metadata.source.credits}.</p><p>{uk ? 'Дані та похідні JSON: CC BY-NC-SA 4.0. Код: MIT.' : 'Data and derived JSON: CC BY-NC-SA 4.0. Code: MIT.'}</p></section>
      </article>
    </div>
  </div>;
}
